### ISSUE TITLE
Error formatting rules with multi-line descriptions

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/sigmafmt#4]
Trying to format a rule like this fails with a yaml parsing error:
```yaml
title: Title
description: |
    My description

    Spans multiple lines
```

With an error
```
2021/04/16 11:29:20 failed to format /<filename>.yml: yaml: line 4: did not find expected key
```
